/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vackapi_jnilearn2_JNILearn2and3 */

#ifndef _Included_org_vackapi_jnilearn2_JNILearn2and3
#define _Included_org_vackapi_jnilearn2_JNILearn2and3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_vackapi_jnilearn2_JNILearn2and3
 * Method:    dataType
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_vackapi_jnilearn2_JNILearn2and3_dataType
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
