/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vackapi_jnilearn2_JNILearn */

#ifndef _Included_org_vackapi_jnilearn2_JNILearn
#define _Included_org_vackapi_jnilearn2_JNILearn




#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_vackapi_jnilearn2_JNILearn
 * Method:    say
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_vackapi_jnilearn2_JNILearn_say
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
